version: "2"

services:
  
  consul0:
    image: wxnrd/did
    hostname: consul0
    privileged: true
    ports:
      - 8500:8500
    networks:
      default:
        ipv4_address: 172.20.0.2

  manager0:
    build: .
    image: wxnrd/did
    hostname: manager0
    privileged: true
    ports:
      - 4000:4000
    volumes:
      - .:/data
    command: ["--cluster-store=consul://172.20.0.2:8500", "--cluster-advertise=172.20.0.3:2375"]
    networks:
      default:
        ipv4_address: 172.20.0.3

  manager1:
    build: .
    image: wxnrd/did
    hostname: manager1
    privileged: true
    volumes:
      - .:/data
    command: ["--cluster-store=consul://172.20.0.2:8500", "--cluster-advertise=172.20.0.4:2375"]
    networks:
      default:
        ipv4_address: 172.20.0.4

  node0:
    image: wxnrd/did
    hostname: node0
    privileged: true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - .:/data
    command: ["--cluster-store=consul://172.20.0.2:8500", "--cluster-advertise=172.20.0.5:2375"]
    networks:
      default:
        ipv4_address: 172.20.0.5

  node1:
    image: wxnrd/did
    hostname: node1
    privileged: true
    volumes:
      - .:/data
    command: ["--cluster-store=consul://172.20.0.2:8500", "--cluster-advertise=172.20.0.6:2375"]
    networks:
      default:
        ipv4_address: 172.20.0.6

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1